create extension if not exists pgcrypto;
create table if not exists users(id uuid primary key default gen_random_uuid(), email text unique not null, display_name text, created_at timestamptz default now());
create table if not exists roles(id uuid primary key default gen_random_uuid(), name text unique not null);
create table if not exists user_roles(user_id uuid references users(id) on delete cascade, role_id uuid references roles(id) on delete cascade, primary key(user_id,role_id));
create table if not exists organizations(id uuid primary key default gen_random_uuid(), name text not null, type text not null);
create table if not exists sites(id uuid primary key default gen_random_uuid(), organization_id uuid references organizations(id), name text not null, active boolean default true);
create table if not exists programs(id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, description text, status text default 'draft');
create table if not exists program_sessions(id uuid primary key default gen_random_uuid(), program_id uuid references programs(id), site_id uuid references sites(id), starts_at timestamptz, ends_at timestamptz, status text default 'planned');
create table if not exists cohorts(id uuid primary key default gen_random_uuid(), session_id uuid references program_sessions(id), name text not null);
create table if not exists students(id uuid primary key references users(id) on delete cascade, active boolean default true);
create table if not exists guardians(student_id uuid references students(id) on delete cascade, guardian_user_id uuid references users(id) on delete cascade, relationship text, primary key(student_id,guardian_user_id));
create table if not exists enrollments(id uuid primary key default gen_random_uuid(), cohort_id uuid references cohorts(id), student_id uuid references students(id), status text default 'active');
create table if not exists concepts(id uuid primary key default gen_random_uuid(), name text unique not null, definition text);
create table if not exists curriculum_units(id uuid primary key default gen_random_uuid(), program_id uuid references programs(id), name text not null, sequence int);
create table if not exists lessons(id uuid primary key default gen_random_uuid(), unit_id uuid references curriculum_units(id), name text not null, sequence int, objective text, professional_term text, technical_definition text, kid_explanation text);
create table if not exists lesson_paths(id uuid primary key default gen_random_uuid(), lesson_id uuid references lessons(id), mode text not null, instructions text not null);
create table if not exists lesson_concepts(lesson_id uuid references lessons(id) on delete cascade, concept_id uuid references concepts(id) on delete cascade, primary key(lesson_id,concept_id));
create table if not exists tools(id uuid primary key default gen_random_uuid(), name text unique not null, sectors text, cost_model text, internet_requirement text, offline_capability text, accessibility_notes text, privacy_notes text, status text default 'pilot');
create table if not exists tool_lesson_mappings(tool_id uuid references tools(id) on delete cascade, lesson_id uuid references lessons(id) on delete cascade, purpose text, primary key(tool_id,lesson_id));
create table if not exists projects(id uuid primary key default gen_random_uuid(), student_id uuid references students(id), title text not null, description text, visibility text default 'private', status text default 'draft');
create table if not exists portfolio_items(id uuid primary key default gen_random_uuid(), student_id uuid references students(id), project_id uuid references projects(id), evidence_type text, reflection text, visibility text default 'private', approved boolean default false);
create table if not exists progress(id uuid primary key default gen_random_uuid(), student_id uuid references students(id), concept_id uuid references concepts(id), status text, evidence_count int default 0, updated_at timestamptz default now(), unique(student_id,concept_id));
create table if not exists attendance(id uuid primary key default gen_random_uuid(), cohort_id uuid references cohorts(id), student_id uuid references students(id), session_date date not null, status text not null, notes text);
create table if not exists assessments(id uuid primary key default gen_random_uuid(), lesson_id uuid references lessons(id), name text not null, rubric jsonb);
create table if not exists assessment_results(id uuid primary key default gen_random_uuid(), assessment_id uuid references assessments(id), student_id uuid references students(id), evidence jsonb, status text);
create table if not exists opportunities(id uuid primary key default gen_random_uuid(), name text not null, description text, age_range text, application_url text, status text default 'active');
create table if not exists partners(id uuid primary key default gen_random_uuid(), name text not null, type text not null, contact_name text, contact_email text, service_area text, status text default 'pending');
create table if not exists meals(id uuid primary key default gen_random_uuid(), site_id uuid references sites(id), service_date date not null, provider_partner_id uuid references partners(id), expected_count int, dietary_notes text, status text);
create table if not exists testimonials(id uuid primary key default gen_random_uuid(), submitted_by uuid references users(id), role text, body text not null, permission_level text, status text default 'submitted');
create table if not exists audit_logs(id uuid primary key default gen_random_uuid(), actor_id uuid references users(id), action text not null, resource_type text, resource_id uuid, created_at timestamptz default now());
insert into roles(name) values ('student'),('guardian'),('instructor'),('volunteer'),('intern'),('mentor'),('guest_speaker'),('site_coordinator'),('program_coordinator'),('curriculum_admin'),('admin') on conflict do nothing;